import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
//import {AutogenerateService } from '../pages/auto-generate-team/auto-generate-team.component'
import { Observable } from 'rxjs';
import { SearchData } from '../spprofileser/search.model';
@Injectable({
  providedIn: 'root'
})
export class AutogenerateService {
  constructor(private http:HttpClient) { }
  // getByIdeaTitleAndRoleName(roleName):Observable<SearchData>{
  //   console.log("in getbyemail of reg service ",roleName);
  //   return this.http.get<SearchData>(`http://13.235.10.115:8084/api/v1/serviceprovider/${roleName}`);
  // }
  //Aniket code
//   posetedIdeas(): Observable <any> {
//    return this.http.get('http://localhost:3000/postAnIdeaDetails');
//  }
//  participantsByRole(role): Observable <any> {
//    return this.http.get('http://localhost:3000/' + role);
//  }
sendAutogeneratedTeam(selectedTeam,title): Observable<any>{
  console.log(title);
  const httpOptions = {
    headers: new HttpHeaders({
      'Content-Type':  'application/json',
    })
  };
  let payload = {
    title: title,
    description: "",
    duration: "",
    domain: "",
    subDomain: "",
    cost: 0,
    role: [
      {
        experience: "",
        noOfPeople: 0,
        skills: ["", ""],
        roleName: ""
      }
    ],
    selectedTeam: [
      {
        name: "krish",
        mobileNo: 0,
        email: "",
        role: {
          role: "",
          experience: "",
          skills: ["", ""]
        },
        chargePerHour: ""
      }
    ],
    appliedTeam: [
      {
        name: "",
        mobileNo: 0,
        email: "",
        role: {
          role: "",
          experience: "",
          skills: ["", ""]
        },
        chargePerHour: ""
      }
    ],
    invitedTeam: [
      {
        name:"",
        mobileNo: "",
        email: "",
        role: {
          role: "",
          experience: "",
          skills: ["",""]
        },
        chargePerHour: ""
      }
    ],
    status: "",
    location: ""
 }
  payload.selectedTeam = selectedTeam;
  console.log(JSON.stringify(payload));
  return this.http.put(`http://13.235.10.115:8083/api/v1/selectedTeam`,JSON.stringify(payload),httpOptions);
}
}
